import type { Approval, FactoryData } from './types'

export const STORAGE_KEY = 'rawplast-factoryos-v1'

export const emptyApprovals = (): Approval[] => [
  { role: 'Customer', status: 'pending' },
  { role: 'Sales', status: 'pending' },
  { role: 'Accounts', status: 'pending' },
  { role: 'Quality', status: 'pending' },
  { role: 'Production', status: 'pending' },
]

export const seedData: FactoryData = {
  customers: [
    {
      id: 'cust-1',
      name: 'Mazoe Foods',
      contact: 'Tariro Moyo',
      phone: '+263 77 212 4100',
      email: 'procurement@mazoe.example',
    },
    {
      id: 'cust-2',
      name: 'Sable Chemicals',
      contact: 'Farai Dube',
      phone: '+263 71 840 2100',
      email: 'stores@sable.example',
    },
    {
      id: 'cust-3',
      name: 'GreenFields Agriculture',
      contact: 'Rudo Chikore',
      phone: '+263 78 502 1900',
      email: 'orders@greenfields.example',
    },
  ],
  orderConfirmations: [
    {
      id: 'oc-1',
      number: 'OC-2026-0148',
      customerId: 'cust-1',
      customerOrderNumber: 'PO-44718',
      receivedDate: '2026-07-15',
      deliveryDate: '2026-07-24',
      orderStatus: 'Repeat Order',
      productDescription: 'Printed LDPE milk sachet film',
      quantityKg: 1200,
      quantityUnits: 0,
      width: 420,
      length: 0,
      gauge: 55,
      tolerance: '±10%',
      paymentTerms: '30 Days',
      specialInstructions: 'Two-colour print. Match approved customer sample.',
      route: ['Extrusion', 'Printing'],
      approvals: [
        { role: 'Customer', status: 'approved', approvedBy: 'Tariro Moyo', approvedAt: '2026-07-15' },
        { role: 'Sales', status: 'approved', approvedBy: 'R. Ncube', approvedAt: '2026-07-15' },
        { role: 'Accounts', status: 'approved', approvedBy: 'P. Sibanda', approvedAt: '2026-07-16' },
        { role: 'Quality', status: 'approved', approvedBy: 'O. Machikiti', approvedAt: '2026-07-16' },
        { role: 'Production', status: 'approved', approvedBy: 'A. Mutota', approvedAt: '2026-07-16' },
      ],
      createdAt: '2026-07-15T08:20:00.000Z',
    },
    {
      id: 'oc-2',
      number: 'OC-2026-0149',
      customerId: 'cust-2',
      customerOrderNumber: 'SC-10991',
      receivedDate: '2026-07-16',
      deliveryDate: '2026-07-27',
      orderStatus: 'New Order',
      productDescription: 'Heavy-duty clear pallet covers',
      quantityKg: 850,
      quantityUnits: 2500,
      width: 1200,
      length: 1800,
      gauge: 100,
      tolerance: '±10%',
      paymentTerms: 'Prepayment',
      specialInstructions: 'Customer sample retained by QA.',
      route: ['Extrusion', 'Bagmaking'],
      approvals: [
        { role: 'Customer', status: 'approved', approvedBy: 'Farai Dube', approvedAt: '2026-07-16' },
        { role: 'Sales', status: 'approved', approvedBy: 'R. Ncube', approvedAt: '2026-07-16' },
        { role: 'Accounts', status: 'pending' },
        { role: 'Quality', status: 'approved', approvedBy: 'O. Machikiti', approvedAt: '2026-07-17' },
        { role: 'Production', status: 'pending' },
      ],
      createdAt: '2026-07-16T10:40:00.000Z',
    },
    {
      id: 'oc-3',
      number: 'OC-2026-0150',
      customerId: 'cust-3',
      customerOrderNumber: 'GF-8824',
      receivedDate: '2026-07-18',
      deliveryDate: '2026-07-30',
      orderStatus: 'Trial Order',
      productDescription: 'Perforated nursery bags',
      quantityKg: 120,
      quantityUnits: 10000,
      width: 220,
      length: 300,
      gauge: 45,
      tolerance: '±10%',
      paymentTerms: 'COD',
      specialInstructions: 'Trial: validate punch pattern before full run.',
      route: ['Extrusion', 'Bagmaking'],
      approvals: emptyApprovals(),
      createdAt: '2026-07-18T09:15:00.000Z',
    },
  ],
  worksOrders: [
    {
      id: 'wo-1',
      number: 'WO-2026-0092',
      orderConfirmationId: 'oc-1',
      customerId: 'cust-1',
      productDescription: 'Printed LDPE milk sachet film',
      quantityKg: 1200,
      quantityUnits: 0,
      machineId: 'machine-ex12',
      expectedRatePerHour: 85,
      formulation: 'LDPE 80% / LLDPE 18% / Additive 2%',
      route: ['Extrusion', 'Printing'],
      status: 'In production',
      createdAt: '2026-07-16T13:00:00.000Z',
    },
  ],
  productionRuns: [
    {
      id: 'run-1',
      worksOrderId: 'wo-1',
      stage: 'Extrusion',
      date: '2026-07-17',
      shift: 'Day',
      machineId: 'machine-ex12',
      operator: 'T. Chari',
      producedKg: 460,
      producedUnits: 0,
      scrapKg: 14,
      downtimeMinutes: 35,
      downtimeCode: 'Screen Change',
      rollCount: 9,
      notes: 'Treatment confirmed both sides.',
      qualityResult: 'Pass',
      createdAt: '2026-07-17T17:40:00.000Z',
    },
    {
      id: 'run-2',
      worksOrderId: 'wo-1',
      stage: 'Extrusion',
      date: '2026-07-18',
      shift: 'Night',
      machineId: 'machine-ex12',
      operator: 'N. Zulu',
      producedKg: 380,
      producedUnits: 0,
      scrapKg: 11,
      downtimeMinutes: 20,
      downtimeCode: 'Waiting for Material',
      rollCount: 7,
      notes: 'Seven rolls transferred to printing queue.',
      qualityResult: 'Pass',
      createdAt: '2026-07-18T05:30:00.000Z',
    },
  ],
  finishedGoodsTransfers: [],
  despatches: [],
  machines: [
    { id: 'machine-ex08', number: 'EX08', type: 'Extrusion', status: 'Available' },
    { id: 'machine-ex12', number: 'EX12', type: 'Extrusion', status: 'Running' },
    { id: 'machine-ex14', number: 'EX14', type: 'Extrusion', status: 'Available' },
    { id: 'machine-pr01', number: 'PR01', type: 'Printing', status: 'Available' },
    { id: 'machine-pr03', number: 'PR03', type: 'Printing', status: 'Maintenance' },
    { id: 'machine-bm09', number: 'BM09', type: 'Bagmaking', status: 'Available' },
    { id: 'machine-bm14', number: 'BM14', type: 'Bagmaking', status: 'Available' },
    { id: 'machine-sl01', number: 'SL01', type: 'Slitting', status: 'Available' },
  ],
}
